### ISSUE TITLE
Cause of the death

### ISSUE THREAD

**Issue by itchyshin** [itchyshin/lifespan_contraception#3]
@Mike-Garratt and @fercol 

Here is the result of a meta-analysis of death causes.

I think the results seem to be the other way around except Other (we expect log risk ratio to be negative when contracepted animals are living longer)

"Other" results look correct as it is negative meaning contracepted animals dying less

<img width="1638" alt="Screenshot 2024-11-17 at 10 51 28 am" src="https://github.com/user-attachments/assets/fb03206c-1bf4-4259-b0f3-430c39dbcba4">

I need to double-check my code

I used the dataset - https://github.com/itchyshin/lifespan_contraception/blob/main/data/zoo2/causeDeathAll.csv

**Comment by Mike-Garratt** [comment]
﻿
Hi @Shinichi ***@***.***>

Thanks for sending this through and chat with you in a little bit. I am pretty sure that the maternal death plot is the wrong way around as looking across the dataset by eye it is obvious that this is higher in non-contracepted in the majority of instances. We have lots of zeros for this variable too. The vast majority of these species also have a very small sample size and when we had plotted this before we had used at least 30 per group as a cut off.

Trying to check that you used the last dataset that Fernando sent as he sent a couple of copies through.

Catch you soon,

Mike

From: Shinichi Nakagawa ***@***.***>
Date: Monday, 18 November 2024 at 6:59 AM
To: itchyshin/lifespan_contraception ***@***.***>
Cc: Mike Garratt ***@***.***>, Mention ***@***.***>
Subject: [itchyshin/lifespan_contraception] Cause of the death (Issue #3)

@Mike-Garratt<https://github.com/Mike-Garratt> and @fercol<https://github.com/fercol>

Here is the result of a meta-analysis of death causes.

I think the results seem to be the other way around except Other (we expect log risk ratio to be negative when contracepted animals are living longer)

"Other" results look correct as it is negative meaning contracepted animals dying less
Screenshot.2024-11-17.at.10.51.28.am.png (view on web)<https://github.com/user-attachments/assets/fb03206c-1bf4-4259-b0f3-430c39dbcba4>

I need to double-check my code

I used the dataset - https://github.com/itchyshin/lifespan_contraception/blob/main/data/zoo2/causeDeathAll.csv

**Comment by fercol** [comment]
Hi Shinichi and Mike,


  I've been looking at the results Shinichi got on GitHub, and I think we should not take the log risk ratio given that, as Mike said, there are too many zeros. Running a quick and dirty analysis calculating simply the difference in cumulative risk (Contra - nonContra) I get that, at all ages, the risks are lower for females under hormonal contraception as well as for males under surgical contraception. For males the differences become positive for chronic diseases at advance ages. Of course, not all these differences are significant.


  Maybe we should take simply the differences: Contra - nonContra, or the relative ratio: (Contra - nonContra) / nonContra



Best,


  Fernando


------------------------------------------------------------------------------------
Dr. Fernando Colchero, Ph.D.
Group Leader: Statistical Demography
Department of Primate Behavior and Evolution
Max Planck Institute for Evolutionary Anthropology (MPI-EVA)
Deutscher Platz 6, 04103, Leipzig, Germany
Phone: +49 (0) 341 3550 231

**Comment by fercol** [comment]
apologies, I didn't send my last email through the GitHub mailing list. Here it is again...


Here are some plots taking the differences. It's definitely not a meta-analysis, but I really don't think the results should differ in direction.  





Best,


  Fernando


------------------------------------------------------------------------------------
Dr. Fernando Colchero, Ph.D.
Group Leader: Statistical Demography
Department of Primate Behavior and Evolution
Max Planck Institute for Evolutionary Anthropology (MPI-EVA)
Deutscher Platz 6, 04103, Leipzig, Germany
Phone: +49 (0) 341 3550 231

**Comment by fercol** [comment]
[CumIncRawFemale.pdf](https://github.com/user-attachments/files/17798806/CumIncRawFemale.pdf)
[CumIncRawMale.pdf](https://github.com/user-attachments/files/17798807/CumIncRawMale.pdf)

**Comment by itchyshin** [comment]
@fercol - thanks for this - now I use risk difference and this makes a lot more sense (also thanks @Mike-Garratt)

This is just preliminary. 

I removed data with only 1 or 2 - at least N in one group had to be 3 (except death at birth - we need to remove all - for this I included ones over N = 1 - i.e. N > 1)


<img width="1511" alt="Screenshot 2024-11-18 at 14 43 49" src="https://github.com/user-attachments/assets/cbfb7ca7-a5d2-4f23-8743-6005172e3f1c">

What we see from this is - there are not clear differences in these categories - Only in Others, we can see contracepted animals are dying slower

**Comment by Mike-Garratt** [comment]
﻿
Hi Shinichi

As far as I saw the effects were sex-specific – can you split it for males and females?



From: Shinichi Nakagawa ***@***.***>
Date: Tuesday, 19 November 2024 at 10:47 AM
To: itchyshin/lifespan_contraception ***@***.***>
Cc: Mike Garratt ***@***.***>, Mention ***@***.***>
Subject: Re: [itchyshin/lifespan_contraception] Cause of the death (Issue #3)

@fercol<https://github.com/fercol> - thanks for this - now I use risk difference and this makes a lot more sense (also thanks @Mike-Garratt<https://github.com/Mike-Garratt>)

This is just preliminary.

I removed data with only 1 or 2 - at least N in one group had to be 3 (except death at birth - we need to remove all - for this I included ones over N = 1 - i.e. N > 1)
Screenshot.2024-11-18.at.14.43.49.png (view on web)<https://github.com/user-attachments/assets/cbfb7ca7-a5d2-4f23-8743-6005172e3f1c>

What we see from this is - there are not clear differences in these categories - Only in Others, we can see contracepted animals are dying slower

**Comment by Mike-Garratt** [comment]
Hi Shinichi,

Is the effect size you are calculating at the moment ignoring all those comparisons where one group has a zero value? For the death at birth we have >10 comparisons for the low timepoint but only a couple where both groups have a value that is not zero

From: Mike Garratt ***@***.***>
Date: Tuesday, 19 November 2024 at 10:53 AM
To: itchyshin/lifespan_contraception ***@***.***>, itchyshin/lifespan_contraception ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [itchyshin/lifespan_contraception] Cause of the death (Issue #3)
﻿
Hi Shinichi

As far as I saw the effects were sex-specific – can you split it for males and females?



From: Shinichi Nakagawa ***@***.***>
Date: Tuesday, 19 November 2024 at 10:47 AM
To: itchyshin/lifespan_contraception ***@***.***>
Cc: Mike Garratt ***@***.***>, Mention ***@***.***>
Subject: Re: [itchyshin/lifespan_contraception] Cause of the death (Issue #3)

@fercol<https://github.com/fercol> - thanks for this - now I use risk difference and this makes a lot more sense (also thanks @Mike-Garratt<https://github.com/Mike-Garratt>)

This is just preliminary.

I removed data with only 1 or 2 - at least N in one group had to be 3 (except death at birth - we need to remove all - for this I included ones over N = 1 - i.e. N > 1)
Screenshot.2024-11-18.at.14.43.49.png (view on web)<https://github.com/user-attachments/assets/cbfb7ca7-a5d2-4f23-8743-6005172e3f1c>

What we see from this is - there are not clear differences in these categories - Only in Others, we can see contracepted animals are dying slower

**Comment by fercol** [comment]
Hi @itchyshin thanks for redoing that. Two things: 
 - We need to separate female-hormonal and male-surgical, otherwise, the important effects disappear, and I am pretty sure the causes are different between both groups.
 - Also, the fact that N is small or even 0 for a given cause of death is an indication that most or all did not die of that cause. We should not exclude any, what is important is that the total N is sufficiently large. I set it up at min 30. If we take out any species with 0 incidence of a given cause, then we are excluding a very important piece of information.

**Comment by itchyshin** [comment]
@Mike-Garratt and @fercol - thank for these pieces of feedback - I will reanalyse the data (I have a student conference next few days but try to do this an hour or so everyday)

**Comment by fercol** [comment]
Thanks a lot, Shinichi!



Best,


  Fernando


------------------------------------------------------------------------------------
Dr. Fernando Colchero, Ph.D.
Group Leader: Statistical Demography
Department of Primate Behavior and Evolution
Max Planck Institute for Evolutionary Anthropology (MPI-EVA)
Deutscher Platz 6, 04103, Leipzig, Germany
Phone: +49 (0) 341 3550 231

**Comment by itchyshin** [comment]
@Mike-Garratt and @fercol - results so far - no clear patterns apart from Others - a few places sig increase (or decrease) of risk in conctracepted animals (more later)

# 1. different times
<img width="1106" alt="Screenshot 2024-11-19 at 10 31 54" src="https://github.com/user-attachments/assets/f8cc39bd-338c-4253-978b-a28b1440dbb5">

# different categories



<img width="1691" alt="Screenshot 2024-11-19 at 10 44 11" src="https://github.com/user-attachments/assets/6f07de83-cf98-4dc1-a65d-79fd360300fd">

**Comment by Mike-Garratt** [comment]
﻿
Hi Shinichi,

Thanks for sending this through. It is starting to look more in line with my thinking although I am still confused by the “Death at birth”, which makes me think there might be a mistake somewhere in the calculations. I can only see two datapoints in the low group where mortality is higher in contracepted group and the others go the opposite direction (higher mortality in the non-contracepted, which is expected).

Can you check the calculations for those?

I would also really like to see the type versus times if possible as this seemed to reveal more in earlier plots.

Are you using a total sample size cut off for inclusion of species? In the meta-analysis of life-expectancy we have a sample size of at least 30 per group to be included in the meta-analysis and that is what Fernando and I have been working on with the cause of death data too.

Thanks again for all your work on this!

Mike

From: Shinichi Nakagawa ***@***.***>
Date: Wednesday, 20 November 2024 at 6:45 AM
To: itchyshin/lifespan_contraception ***@***.***>
Cc: Mike Garratt ***@***.***>, Mention ***@***.***>
Subject: Re: [itchyshin/lifespan_contraception] Cause of the death (Issue #3)

@Mike-Garratt<https://github.com/Mike-Garratt> and @fercol<https://github.com/fercol> - results so far - no clear patterns apart from Others - a few places sig increase (or decrease) of risk in conctracepted animals (more later)

1. different times
Screenshot.2024-11-19.at.10.31.54.png (view on web)<https://github.com/user-attachments/assets/f8cc39bd-338c-4253-978b-a28b1440dbb5>
different categories
Screenshot.2024-11-19.at.10.44.11.png (view on web)<https://github.com/user-attachments/assets/6f07de83-cf98-4dc1-a65d-79fd360300fd>

**Comment by fercol** [comment]
Hi @itchyshin, thanks for pushing through! And sorry to keep pestering you... I do agree with Mike, I believe that, as it is now, it is excluding cases when in one group there were no deaths of a given cause. This is a multinomial process, where the only N that matters is the total N, which measures the total exposures. A 0 means a true 0 incidence. As a result, we are missing many points. There should be the same number of species and thus points for all causes of death at all three levels (low, med, upp). For instance, the mean difference for Birth at death Low is -0.004, but in the plot it appears as negative, when most of the points fall on the negative side. A weighted average, weighted by the total N of contracepted gives -0.014. Sorry for my rambling...

**Comment by itchyshin** [comment]
@fercol and @Mike-Garratt - please, comments coming - hugely appreciated and helpful in my thinking process (I am putting it here so I can get immediately comments - which will will help my analysis done quicker than otherwise)

I still used the criteria that for given a cause, they at least have to have 1 entry - this is becuase effect sizes do not work if we do not have any entries in a particular cause - this is becuase one cannot calculate uncertainly if you have zero entries in one group (but I will try to do what you suggested )

So risk ratio or difference, it is basically 2 x 2 contengecy table - comparing two groups - one cannot really calculate if you have zero entries in one group. Yet, we could do some calculations by adding 0.5 artificial - and this was what I was originally doing and give you wildly wrong results. 

Having said this, let me try what I can do.

**Comment by fercol** [comment]
Hi Shinichi,


   It seems that that this is not the right analysis if we have to exclude when there are no incidences. We need to think about the best way to show the differences in incidences without excluding important information. 


   Just one clarification, when analyzing competing risks and cumulative incidences the N is that of the total exposures. So the N by cause that I sent you with the data is misguided, since the correct N is the total number of exposures (i.e., Contra_Total_N and noContra_Total_N). This is because we are looking at the cumulative proportion of cases for the given cause at the different ages. 


   I know you're in the middle of a student conference, but I'll be happy to have a chat over zoom if you have a chance this or next week, in case that can be helpful.



Best,


  Fernando


------------------------------------------------------------------------------------
Dr. Fernando Colchero, Ph.D.
Group Leader: Statistical Demography
Department of Primate Behavior and Evolution
Max Planck Institute for Evolutionary Anthropology (MPI-EVA)
Deutscher Platz 6, 04103, Leipzig, Germany
Phone: +49 (0) 341 3550 231

**Comment by itchyshin** [comment]
@fercol - thanks for this clarification - let's see whether I can figure this out (I think I know what to do now) - if not, I will set up a meeting with you next week. Thanks!

**Comment by itchyshin** [comment]
@fercol and @Mike-Garratt - thanks for your patience - I was wrongly using N columns (now I use total N rather than N for each category)

Hopefully, these look more reasonable.

# Low vs Mid vs Upper
Apart from Chronic Diseas - everything is sig. at Upper

<img width="1656" alt="Screenshot 2024-11-22 at 10 22 00" src="https://github.com/user-attachments/assets/b56c73e7-e9fc-4fa8-bb3d-4b75a70b2901">


# Different types of castration

Some interesting patterns in Traum and Infectious Diseases

<img width="1604" alt="Screenshot 2024-11-22 at 10 30 32" src="https://github.com/user-attachments/assets/a1dbfa84-6796-47a3-863f-11f55e06bdf1">

**Comment by fercol** [comment]
@itchyshin Wow, that's great! The results are very interesting! On the contrary, thank you for your patience!

**Comment by Mike-Garratt** [comment]
Awesome, thanks @itchyshin ! I have started putting some paragraphs together on the new results and we can plan how we want to present everything. If it's OK I'll get back to you this week with thoughts on that.

Thanks again for all your work!

Mike
