### ISSUE TITLE
pre-post analysis (lifespan)

### ISSUE THREAD

**Issue by itchyshin** [itchyshin/lifespan_contraception#6]
@Mike-Garratt  sorry for the delay - there is no good statistical evidence in our dataset that animals live longer if you control for phylogeny. As you pointed out probably primates are causing this. The analysis shows there is 40% phylogenetic effect as you might have expected

<img width="641" alt="Screenshot 2024-12-17 at 11 44 36" src="https://github.com/user-attachments/assets/b3041894-14cb-422f-95e6-9af562c2761b" />
<img width="1011" alt="Screenshot 2024-12-17 at 11 44 25" src="https://github.com/user-attachments/assets/dc593857-036b-413c-b1e8-81d14cf034a5" />

Anything you may want to write? - one thing is whatever we may do, it probably won't change things very much - do you want to move this to suppl?  anyway, I will move to other analyses and figs for now

**Comment by Mike-Garratt** [comment]
Hi Shinichi

Just about to drive the kids to school. Which analysis is this referring to? The pre or post sexual maturity one?

Thanks

Mike

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Shinichi Nakagawa ***@***.***>
Sent: Wednesday, December 18, 2024 8:29:40 AM
To: itchyshin/lifespan_contraception ***@***.***>
Cc: Mike Garratt ***@***.***>; Mention ***@***.***>
Subject: [itchyshin/lifespan_contraception] pre-post analysis (lifespan) (Issue #6)


@Mike-Garratt<https://github.com/Mike-Garratt> sorry for the delay - there is no good statistical evidence in our dataset that animals live longer if you control for phylogeny. As you pointed out probably primates are causing this. The analysis shows there is 40% phylogenetic effect as you might have expected

Screenshot.2024-12-17.at.11.44.36.png (view on web)<https://github.com/user-attachments/assets/b3041894-14cb-422f-95e6-9af562c2761b> Screenshot.2024-12-17.at.11.44.25.png (view on web)<https://github.com/user-attachments/assets/dc593857-036b-413c-b1e8-81d14cf034a5>

Anything you may want to write? - one thing is whatever we may do, it probably won't change things very much - do you want to move this to suppl? anyway, I will move to other analyses and figs for now

**Comment by itchyshin** [comment]
Yes @Mike-Garratt - The pre or post sexual maturity one

Sorry this is a bit the other way around - actually log(after/before) - I should have showed log(before/after) but either way it is not significant - quite far from it

**Comment by itchyshin** [comment]
in the right direction - log(before) - log(after)

<img width="1009" alt="Screenshot 2024-12-17 at 13 25 45" src="https://github.com/user-attachments/assets/c60ffdeb-58fe-4383-b4d8-6427e74691cc" />

**Comment by Mike-Garratt** [comment]
Hi Shinichi,

Thanks for sending this through. Do you think we should try and drop the primates from the analysis and see if that makes a difference? We would obviously need to explain that, i.e. there was an effect of phylogeny on the degree of lifespan change with sterilization before or after sexual maturity, with sterilization before sexual maturity influencing lifespan extension in several mammalian clades  but not primates etc.

Is it lots of work to split the analysis into orders or is very easy? If its lots of work we can just leave it.

Also I realized that we have Panthera leo and Mandrillus sphinx included where the ainimals are vasectomized, although it probably wont make much of a difference.

Thanks for all your efforts with this!

Mike

From: Shinichi Nakagawa ***@***.***>
Date: Wednesday, 18 December 2024 at 9:27 AM
To: itchyshin/lifespan_contraception ***@***.***>
Cc: Mike Garratt ***@***.***>, Mention ***@***.***>
Subject: Re: [itchyshin/lifespan_contraception] pre-post analysis (lifespan) (Issue #6)

in the right direction - log(before) - log(after)
Screenshot.2024-12-17.at.13.25.45.png (view on web)<https://github.com/user-attachments/assets/c60ffdeb-58fe-4383-b4d8-6427e74691cc>

**Comment by itchyshin** [comment]
@Mike-Garratt - OK - let me try - will do this the first thing tomorrow morning

**Comment by Mike-Garratt** [comment]
Excellent, thanks so much Shinichi. I think if we have some explanation about the phylogenetic signal that could be cool.

Thanks also for the other analysis. I agree that it might be good if we just use this as a response to the reviewer but not add it to the main paper or put it as supplementary.

Let me know if you have any other questions or there are additional things I can help with.

Cheers
Mike

From: Shinichi Nakagawa ***@***.***>
Date: Wednesday, 18 December 2024 at 1:03 PM
To: itchyshin/lifespan_contraception ***@***.***>
Cc: Mike Garratt ***@***.***>, Mention ***@***.***>
Subject: Re: [itchyshin/lifespan_contraception] pre-post analysis (lifespan) (Issue #6)

@Mike-Garratt<https://github.com/Mike-Garratt> - OK - let me try - will do this the first thing tomorrow morning

**Comment by Mike-Garratt** [comment]
In addition to my comment below, when you test dropping primates can you also remove Panthera leo too? I think we should probably remove that and Mandrils as we know that they are mainly vasectomized.

Thanks

From: Mike Garratt ***@***.***>
Date: Wednesday, 18 December 2024 at 8:29 PM
To: itchyshin/lifespan_contraception ***@***.***>, itchyshin/lifespan_contraception ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [itchyshin/lifespan_contraception] pre-post analysis (lifespan) (Issue #6)
Excellent, thanks so much Shinichi. I think if we have some explanation about the phylogenetic signal that could be cool.

Thanks also for the other analysis. I agree that it might be good if we just use this as a response to the reviewer but not add it to the main paper or put it as supplementary.

Let me know if you have any other questions or there are additional things I can help with.

Cheers
Mike

From: Shinichi Nakagawa ***@***.***>
Date: Wednesday, 18 December 2024 at 1:03 PM
To: itchyshin/lifespan_contraception ***@***.***>
Cc: Mike Garratt ***@***.***>, Mention ***@***.***>
Subject: Re: [itchyshin/lifespan_contraception] pre-post analysis (lifespan) (Issue #6)

@Mike-Garratt<https://github.com/Mike-Garratt> - OK - let me try - will do this the first thing tomorrow morning

**Comment by itchyshin** [comment]
@fercol and @jostaerk - now I realise the dataset I have is probably smaller than what @jostaerk has in this fig

<img width="819" alt="Screenshot 2024-12-17 at 16 56 00" src="https://github.com/user-attachments/assets/28e0d315-1af6-48bb-b0e2-3dd06409cf53" />

The dataset I have has 41 species but this fig shows 46 species

[timing_male.csv](https://github.com/user-attachments/files/18184071/timing_male.csv)

Maybe I am using a wrong dataset?

**Comment by itchyshin** [comment]
@Mike-Garratt - I did analysis without primates - it is sig but we need a strong justification to do this (also, note that phylogenetic variance gets reduced a lot - compared earlier - which is expected)

<img width="648" alt="Screenshot 2024-12-18 at 07 42 48" src="https://github.com/user-attachments/assets/3d37093d-44ad-4a58-879d-d18aa6ee0fbf" />
<img width="977" alt="Screenshot 2024-12-18 at 07 42 38" src="https://github.com/user-attachments/assets/1699288d-1aae-438b-8b2d-2993a1bd7a3e" />

**Comment by fercol** [comment]
@itchyshin @jostaerk @Mike-Garratt Johanna is finishing the plots and will send an update. Maybe the difference in number of species is because she is combining males and females... Also, I believe she was using the old phylogeny. Let's see when she sends the updated figure with the latest phylogeny.

**Comment by itchyshin** [comment]
Thanks for letting us know @fercol

**Comment by Mike-Garratt** [comment]
Hi Shinichi,

Excellent, many thanks for doing this. I think we will need to present the initial analysis saying that there is no overall effect but a strong phylogenetic signal. This is because primates do not show a greater increase in life-expectancy with pre-sexual maturity sterilization, but across the remaining species you do see a stronger effect on lifespan with early-life sterilization.

Does that make sense?

Thanks
Mike

From: Shinichi Nakagawa ***@***.***>
Date: Thursday, 19 December 2024 at 3:45 AM
To: itchyshin/lifespan_contraception ***@***.***>
Cc: Mike Garratt ***@***.***>, Mention ***@***.***>
Subject: Re: [itchyshin/lifespan_contraception] pre-post analysis (lifespan) (Issue #6)

@Mike-Garratt<https://github.com/Mike-Garratt> - I did analysis without primates - it is sig but we need a strong justification to do this (also, note that phylogenetic variance gets reduced a lot - compared earlier - which is expected)
Screenshot.2024-12-18.at.07.42.48.png (view on web)<https://github.com/user-attachments/assets/3d37093d-44ad-4a58-879d-d18aa6ee0fbf> Screenshot.2024-12-18.at.07.42.38.png (view on web)<https://github.com/user-attachments/assets/1699288d-1aae-438b-8b2d-2993a1bd7a3e>
